### ISSUE TITLE
variable message dont work? 

### ISSUE THREAD

**Issue by milo123milo** [carpedm20/fbchat#107]
Whenever i try to print `message` outside class it just displays error that `message is not defined`??? 
How to solve this?? 

```

import fbchat
#subclass fbchat.Client and override required methods
class EchoBot(fbchat.Client):

    

    def __init__(self,email, password, debug=True, user_agent=None):
        fbchat.Client.__init__(self,email, password, debug, user_agent)

    def on_message(self, mid, author_id, author_name, message, metadata):
        self.markAsDelivered(author_id, mid) #mark delivered
        self.markAsRead(author_id)#mark read
        
         

        print("%s said: %s"%(author_id, message))

        
            
        if str(author_id) != str(self.uid):
            self.send(author_id,message)



bot = EchoBot("ID", "Pass")

bot.listen()

```

**Comment by madsmtm** [comment]
I would recommend [stackoverflow](https://stackoverflow.com) for these kind of general python questions. Try asking something like "how do you access a variable outside a class in python", or something like that

**Comment by Bankde** [comment]
You can search it using google. These questions are very general and shouldn't be hard to find the answer.
https://www.google.co.th/search?q=python+global+variable&ie=utf-8&oe=utf-8&client=firefox-b-ab&gws_rd=cr&ei=FymbWLhLjMu-BNatlcgN

You might want to start with
https://www.youtube.com/watch?v=tKTZoB2Vjuk
https://www.codecademy.com/learn/python
That's how I started learning python. They are pretty good. There might not be some information like "global" variable in tutorial because it's usually bad practice to use global, use class is better.

By the way, please stick to the old issue, don't create new one.
Good luck learning.

**Comment by milo123milo** [comment]
i find the global variable but it does not still work :P

**Comment by Bankde** [comment]
This works on python 2.7

```
a=0
class Test:
        def __init__(self):
                self.a=10

        def on_message(self, sth):
                global a
                self.a = 5
                a = sth

# a is 0
print a

t = Test()
# t.a is 10
print t.a

t.on_message(100)
# a is now 100
print a
# t.a is now 5 (local var in class)
print t.a
```
