### ISSUE TITLE
Incorrectly closed without checking - Logins broken again as of 6/23/2017 #162

### ISSUE THREAD

**Issue by amplogik** [carpedm20/fbchat#168]
madsmtm closed 162 without apparently checking the veracity of the response.   I was using echobot from the documented example at https://fbchat.readthedocs.io/en/master/examples.html#basic-example, which I have included below for completeness.  

I am sorry to say, but  "Check out the documentation" is not helpful if the documentation and examples do not detail said parameter, and if the code was working fine for several weeks with no changes and it suddenly stopped.

No suggestion was given for version,  or how this parameter is to be supplied or why it suddenly is required with no updates or changes to the python libraries.   A link to where this is detailed in regards to your sample applications would be very helpful, seeing as this parameter doesn't actually appear in them.

Perhaps someone would be so kind as to direct me to this documentation that explains why I need a new parameter in previously working code.   I would be most obliged.

Also, if there are new critical parameters required,  would it not be prudent to update the examples?

Thank you in advance

----------
madsmtm commented 3 days ago
A lot of fbchat's code has been updated in the new version, you're probably passing 0 to the parameter max_tries somewhere. Check out the documentation

Also, next time, remember to include some of your code ;)
----------
##########
# echobot.py
##########

from fbchat import log, Client

# Subclass fbchat.Client and override required methods
class EchoBot(Client):
    def onMessage(self, author_id, message, thread_id, thread_type, **kwargs):
        self.markAsDelivered(author_id, thread_id)
        self.markAsRead(author_id)

        log.info("Message from {} in {} ({}): {}".format(author_id, thread_id, thread_type.name, message))

        # If you're not the author, echo
        if author_id != self.uid:
            self.sendMessage(message, thread_id=thread_id, thread_type=thread_type)

client = EchoBot("<email>", "<password>")
client.listen()

----------
Results
----------
user@wwwserver# ./echobot.py
Logging in ...
Traceback (most recent call last):
File "./echobot.py", line 21, in 
bot = EchoBot("", "")
File "./echobot.py", line 8, in init
fbchat.Client.init(self,email, password, debug, user_agent)
File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 73, in init
self.login(email, password, max_tries)
File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 318, in login
raise Exception('Cannot login: max_tries should be at least one')
Exception: Cannot login: max_tries should be at least one

WAS working previously, no update.

**Comment by madsmtm** [comment]
I am sorry if I've been unclear or perhaps even rude, I didn't mean to, and I hope you'll forgive me ;)

Regarding your issue, then it's because in the new version, almost all the initialisation parameters have been changed/updated. The debug parameter is no longer present, so when you pass something like `EchoBot('<email>', '<password>', '<user_agent>', False)`, which was valid in earlier versions (!), the `Client`'s `__init__` method is now structured like this: `Client(email, password, user_agent=None, max_tries=5, session_cookies=None, logging_level=logging.INFO)`.
That means it'll think you meant to set the fourth parameter `max_tries` to `False`, which is the same as `0`, and which is invalid.

In case the explanation was unclear, to fix it, remove `False` from `EchoBot('<email>', '<password>', '<user_agent>', False)`. The client is no longer in debug mode by default!

When I said you should "remember to include some of your code", I assumed you used the example from earlier versions, which I knew wasn't going to work. Again, I'm sorry if I've caused you unnecessary trouble!

And you're right, currently there's not a full explanation of all the init parameters (and a lot of vital documentation is still missing!), but you can check them out [here](https://fbchat.readthedocs.io/en/master/api.html#fbchat.Client), if you want ;)

**Comment by amplogik** [comment]
Awesome, thank you so much.     Unfortunately the existing documentation is lagging behind this change, which is not uncommon in projects, so there wasn't anywhere I could find this info.   Providing it is of immense help.   I'm sure that someone will update the doc and example code soon.  :)

The login now works great that I know what to pass.  However I am still getting some errors after that point.  First is that I can't pass logging_level, it complains that the keyword logging is unknown, so I dro that in the code below, and the login works fine.    However, I still get an error after connect. However, the echo works now, so this gets me over this hump.   Much obliged.  :)

I have included the error below for information purposes.

Also, for my notes... 

Should it be: logging_level=logging.INFO or perhaps logging_level=INFO?   It's a bit unclear from the context above?

Error on connect after login:
```
Exception in parsing of {u'made': u'1498760596276', u'type': u'qprimer'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 1274, in _parseMessage
    self.onQprimer(ts=m.get("made"), msg=m)
TypeError: onQprimer() got an unexpected keyword argument 'ts'
```


Code:
```
from fbchat import log, Client

# Subclass fbchat.Client and override required methods
class EchoBot(Client):
    def onMessage(self, author_id, message, thread_id, thread_type, **kwargs):
        self.markAsDelivered(author_id, thread_id)
        self.markAsRead(author_id)

        log.info("Message from {} in {} ({}): {}".format(author_id, thread_id, thread_type.name, message))

        # If you're not the author, echo
        if author_id != self.uid:
            self.sendMessage(message, thread_id=thread_id, thread_type=thread_type)

client = EchoBot("user@example.com", "fake_password", user_agent=None, max_tries=5, session_cookies=None)
client.listen()
```

**Comment by madsmtm** [comment]
About the logging level:
The `logging` part comes from a python module called `logging`
So, to use `logging.DEBUG`, you have to write `import logging` at the top of your code :)

About the `onQprimer` error:
This was noticed in #166 and fixed subsequently. Update `fbchat` ;) (You can do that by typing `pip install --upgrade fbchat` in your terminal)

Also, in case you didn't know, when calling a function or initialising a class, like `Client`, you don't have to input all the parameters. Some of them are optional. What this means is that, the line
```
client = EchoBot("user@example.com", "fake_password", user_agent=None, max_tries=5, session_cookies=None)
```
is equivalent to
```
client = EchoBot("user@example.com", "fake_password")
```
since you're using the default values. If you want to know more about this, I'd suggest a search for `args and kwargs` on google ;)

**Comment by madsmtm** [comment]
Assuming the above did it for you ;)
