### ISSUE TITLE
Got exception while listening

### ISSUE THREAD

**Issue by JarbasAI** [carpedm20/fbchat#175]
happens randomly, not sure how to reproduce

i have a bot running 24/7, today it was down and this was last log, i know it has happened before and i just ignored it

`
2017-07-06 04:56:21,530 - client - ERROR - Got exception while listening
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 1430, in doOneListen
    content = self._pullMessage(self.sticky, self.pool)
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 1242, in _pullMessage
    j = checkRequest(self._get(ReqUrl.STICKY, data))
  File "/usr/local/lib/python2.7/dist-packages/fbchat/utils.py", line 157, in checkRequest
    raise Exception('Error when sending request: Got {} response'.format(r.status_code))
Exception: Error when sending request: Got 502 response
`

**Comment by madsmtm** [comment]
Seems like something that's virtually impossible to fix, like #130. If anyone figures out why, I'd love to know, but other than that, I think the only thing we can do is just catch the error, and the do a re-login, or simply just re-login every, say, 6 hours.

**Comment by Bankde** [comment]
Im working on this one right now (since I need 24/7 too haha)

I observe that facebook starts sending weird response that contains fb_dtsg after running like days.
I think this issue is same with this one and they have already fixed it.
https://github.com/Schmavery/facebook-chat-api/issues/202

Here is the code:
https://github.com/carpedm20/fbchat/pull/178
Pray that there's nothing wrong with it XD
I think I still need to test for few weeks. I will confirm it here then you can merge that pull request.

PS: It's funny that I also thumb-up'ed the comment in that issue. Somehow I completely forgot about it. -facepalm-

**Comment by madsmtm** [comment]
Thanks for you work, this'll become really handy :)

**Comment by Bankde** [comment]
Note: I recently met an error IF nothing had been sent for 3 days then I sent a message.
`Exception: Error #1357004 when sending request: Please try closing and re-opening your browser window.`
It seems that updating fb_dtsg from message isn't enough in case that fbchatClient is afk'ing for long time.
Request facebook.com to get new fb_dtsg could help. Im quite busy right now, will test and fix this later.
