### ISSUE TITLE
Error #1545012

### ISSUE THREAD

**Issue by victorromao** [carpedm20/fbchat#181]
Traceback (most recent call last):
  File "/root/PycharmProjects/little-boy/main.py", line 16, in <module>
    a.basico()
  File "/root/PycharmProjects/little-boy/main.py", line 13, in basico
    self.sendMessage('oi', thread_id='1445803345476440')
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 856, in sendMessage
    return self._doSendRequest(data)
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 824, in _doSendRequest
    j = checkRequest(self._post(ReqUrl.SEND, data))
  File "/usr/local/lib/python3.5/dist-packages/fbchat/utils.py", line 170, in checkRequest
    check_json(j)
  File "/usr/local/lib/python3.5/dist-packages/fbchat/utils.py", line 149, in check_json
    raise Exception('Error #{} when sending request: {}'.format(j['error'], j['errorDescription']))
Exception: Error #1545012 when sending request: Ocorreu um erro temporário, tente novamente.

**Comment by madsmtm** [comment]
Can you please provide steps to reproduce? Does this happen every time you try to send a message, or only when certain conditions are met? In any case, a temporary fix would be to resend the message, or doing a re-login

**Comment by madsmtm** [comment]
Also, see [Error Codes](https://developers.facebook.com/docs/messenger-platform/send-api-reference/errors) (<- is not the same as `fbchat`, but some things may be similar). This seems like it's an _Internal Error_ (I'm guessing from the error message), so it could very likely be an error on Facebook's end

**Comment by brando-x** [comment]
I installed fbchat using the pip. The error only occurs while trying to send message. I did the installation manually and continue with the error.

**Comment by madsmtm** [comment]
Does it occur every time you send a message? Are you sure you're using the right `thread_id`s and `thread_type`s? Please show some code ;)

**Comment by hellsins** [comment]
Today I have the same error as above.
This is my code (I'm sure I've entered the correct thread_id and thread_type)

`
From fbchat import Client
From getpass import getpass

Client = Client (input ("Username:"), getpass ("Password:"))
Thread_id = '1527486310630335'
Thread_type = 'ThreadType.GROUP'

Print ("sending .....")
Client.sendMessage ('spam no reply', thread_id = thread_id, thread_type = thread_type)
Print ("Done!")

Client.logout ()
Print ("Logout successfull")
`

But it only happens when I send a message to the group (if sent to the user is normal). This is the error of the code above

`
Traceback (most recent call last):
  File "fb.py", line 11, in <module>
    Client.sendMessage ('spam no reply', thread_id = thread_id, thread_type = thread_type)
  File "/usr/lib/python3.6/site-packages/fbchat/client.py", line 864, in sendMessage
    Return self._doSendRequest (date)
  File "/usr/lib/python3.6/site-packages/fbchat/client.py", line 825, in _doSendRequest
    J = checkRequest (self._post (ReqUrl.SEND, data))
  File "/usr/lib/python3.6/site-packages/fbchat/utils.py", line 170, in checkRequest
    Check_json (j)
  File "/usr/lib/python3.6/site-packages/fbchat/utils.py", line 149, in check_json
    Raise Exception ('Error # {} when sending request: {}'. Format (j ['error'], j ['errorDescription']))
Exception: Error # 1545012 when sending request: There was a temporary error, please try again.
`
thanks...

**Comment by madsmtm** [comment]
@hellsins, you're setting the thread_type to a string, not the actual value. You need to `from fbchat.models import *` and then use `ThreadType.GROUP`, not `'ThreadType.GROUP'` with the quotes ;)

**Comment by hellsins** [comment]
thank @madsmtm. I did it. great

**Comment by lolo1394** [comment]
Hello everybody,
I am stuck at the same point as you but yet I did not make the mistakes you made. Do you have a solution to my problem? Thank you

-----------------------------CODE---------------------------------
from getpass import getpass
import fbchat
from fbchat import Client
from fbchat.models import *
import re
fbchat._util.USER_AGENTS    = ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"]
fbchat._state.FB_DTSG_REGEX = re.compile(r'"DTSGInitialData",\[\],{"token":"(.*?)"')
fbchat._state.revision = 0 


# Log the user in
client = fbchat.Client("l***************", "******************")
Thread_id = "614984********"
Thread_type = ThreadType.GROUP
message_id = client.send(Message("oui"),thread_id=Thread_id,thread_type=Thread_type)

**Comment by MohamadOday** [comment]
@lolo1394 
try adding text argument to Message() so it will be like this:
`client.send(Message(text="oui"),thread_id=Thread_id,thread_type=Thread_type)`

**Comment by lolo1394** [comment]
unfortunately it is always the same thing and the same mistake ... 
I feel like I've tried everything

**Comment by MohamadOday** [comment]
Well this maight be the last thing you can do wich is changing the user agent to an older one like this one :
`Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.11) Gecko/20071204 Ubuntu/7.10 (gutsy) Firefox/2.0.0.11`

and making sure you can send the message to the specified thread_id (I suggest trying to send it to yourself if you want to test this fix out)
