### ISSUE TITLE
ThreadColor Enums Error

### ISSUE THREAD

**Issue by ekohilas** [carpedm20/fbchat#220]
Currently, The ThreadColor Enums only support a given set of colours, however previous versions of messenger allowed for any thread colour to be set through a post request, and so currently the code breaks when thread info is called for such a thread.

There's a couple of ways this could be solved:
* Whenever the thread color is passed back to the user, it should be passed back as a string instead. The Enum would still exist to allow the user to send the correct data when changing the thread colour. This feels like the more correct option and would be better for the future, but would break backwards compatibility (Which wouldn't be too bad as other improvements could be made too)
* Make the type of all thread colours strings
* Whenever a new ThreadColor is seen, the enum could be extended to include it
https://stackoverflow.com/a/35899963. This wouldn't break backwards compatibility, but would require the aenum package, and seems more hacky.

**Comment by madsmtm** [comment]
I see that that's a problem, but I'd really like to avoid breaking backwards compatability for as long as possible. Maybe we should just log the exception instead of raising it, and then have the threadcolor be `None` or a string? This would be a tempoary fix, until we decide to break backwards compatability anyways.
When we do decide to do so, please remind me, and make this system better ;)
