### ISSUE TITLE
How to print 3 lines log of conversation?

### ISSUE THREAD

**Issue by japiotr123** [carpedm20/fbchat#228]

**Comment by madsmtm** [comment]
Maybe you could elaborate on what you mean? Do you want to print the last three lines of conversation in a specific chat? In all chats? Print three lines of messages every time there is a new message?

**Comment by japiotr123** [comment]
I know how to make 3 lines appear
The reason is that the chat log is downloaded to the file
Translated by google translate:

**Comment by madsmtm** [comment]
I'm sorry, I don't really understand what you mean. Maybe you could show some code, describing what you're trying to do? If your problem is specific to the Raspberry PI, I can't help you ;)

**Comment by japiotr123** [comment]
This code have 320 lines (it isn't only fbchat :( )
This problem is not specific to the raspberry pi
How to download for example chat not grouped from last 1 day

**Comment by DeltaF1** [comment]
It sounds like your problem might have to do with how you're writing the messages to your file. May I suggest looking into python's file flushing to make sure that you're actually writing to the file every time a message comes in? If you want help with this you're really going to need to give us more context for what you're doing, as it's very unclear exactly what the problem is.
