### ISSUE TITLE
client.listen() active all the time

### ISSUE THREAD

**Issue by 2FWAH** [carpedm20/fbchat#271]
Hello community,

It's safe to use client.listen(markAlive=True) all the time?

Some of you notice issues (like logout, ban or rate limiting?) on your account?

Maintainer, feel free to close this issue if it's not the right place to ask.

Bye

**Comment by madsmtm** [comment]
I've been running my server 24/7 (Well, I've had a lot of downtime, but you get the idea) for the past six months, where I've had four Facebook accounts running with `listen`. In that time, I've probably been a pretty bad Facebook citizen. I've been temporarily muted/banned several times because I accidentally started spamming Facebook, but again, only temporarily. So, if by "safe" you mean "safe from losing my account", I'd say you're pretty decked out, and besides, if anything REALLY bad happens, I'm sure you would be able to contact them and get your account reactivated.

Regarding stability, then I'm not sure it's "safe", as in we've had, and still have, a few issues to resolve there.

**Comment by Bankde** [comment]
Confirmed, I have been running for 5 months.
Got temporarily muted once because my program ran out of flow and started spamming like 500+ messages in few minutes XD

If you worry about security of your account, don't use real account.

**Comment by 2FWAH** [comment]
Thank you for your opinion :+1: 

I think Facebook is not stupid and knows that a user logged in 24/7 is not human. Seems tolerated for now.

@madsmtm you can close the issue or wait for other opinions, whatever you want.
