### ISSUE TITLE
request error

### ISSUE THREAD

**Issue by arasi27676271** [carpedm20/fbchat#272]
it always says `bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`
but i had already install lxml
how can i fix it

**Comment by madsmtm** [comment]
Hmm, how are you installing `lxml`? Can you perhaps try `pip install --upgrade fbchat`, and give us the output?

**Comment by arasi27676271** [comment]
sorry, i have a exam in 3 day , so i forgot to answer......
This is the first output 
```
File "/usr/local/lib/python3.5/dist-packages/fbchat-1.3.3-py3.5.egg/fbchat/client.py", line 73, in __init__
  File "/usr/local/lib/python3.5/dist-packages/fbchat-1.3.3-py3.5.egg/fbchat/client.py", line 382, in login
  File "/usr/local/lib/python3.5/dist-packages/fbchat-1.3.3-py3.5.egg/fbchat/client.py", line 242, in _login
  File "/usr/local/lib/python3.5/dist-packages/beautifulsoup4-4.6.0-py3.5.egg/bs4/__init__.py", line 165, in __init__
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```
this is the pip list
```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
akad (0.11.1)
beautifulsoup4 (4.6.0)
certifi (2018.1.18)
chardet (3.0.4)
curve (0.1.0)
enum34 (1.1.6)
fbchat (1.3.6)
github3.py (0.9.6)
idna (2.6)
line (0.8.2)
linepy (3.0.8)
lxml (4.2.1)
pip (9.0.3)
pyasn1 (0.4.2)
PyQRCode (1.2.1)
requests (2.18.4)
rsa (3.4.2)
setuptools (20.7.0)
six (1.11.0)
thrift (0.11.0)
uritemplate (3.0.0)
uritemplate.py (3.0.2)
urllib3 (1.22)
wheel (0.29.0)
```
I am really not good at py......

**Comment by madsmtm** [comment]
Hmm, I don't know what could cause this, though it's most likely not the because of `fbchat`, try testing if the following code (taken almost purely from [here](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)) gives the same error:
```py
from bs4 import BeautifulSoup

html_doc = """
<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""

soup = BeautifulSoup(html_doc, 'lxml')
```

If the above still fails, perhaps you should take it up with [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/), or create an issue on [their bugtracker](https://bugs.launchpad.net/beautifulsoup/) (Note that I don't know how they prefer to deal with installation issues, so you should research that beforehand)

Also make sure that the `pip` command you are using is installing modules into the same python version that you are using. (`pip` might be symlinked to `pip3.5`, while `python` could be symlinked to `python2.7`)

**Comment by arasi27676271** [comment]
sorry.....i just finish the exam today 
and i fix it
i think the problem is in pip
thank u
