### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Ewa321** [carpedm20/fbchat#304]
Hey @carpedm20 ! I'm using fbchat for a week now. I know that fbchat works by emulating the browser but:

1.How do you keep fbchat running? Will there be a time that we can no longer login using fbchat?

2.After the data leak that happened months ago, Facebook announced updates on the developer platform to improve privacy and security. Will it affect fbchat?

**Comment by madsmtm** [comment]
I think there's always going to be ways of emulating a browser, to do automated tasks. Even if Facebook's source code gets so convoluted that we can't figure out how to do the most simple things, there's always going to be the option of running [Selenium](https://www.seleniumhq.org/), for example, or even more hacky things.
The two biggest issues are willingness (if there's no project maintainers, there's no project) and legal issues. If Facebook contacts @carpedm20 and asks him to take down the project, he will and should, and that's probably going to be the end.
I don't think the updates on the developer platform if going to affect us, since it's after all very different platforms. The developer platform is for global use, you can reach, and gather data about, millions of people, if not more. With fbchat, you're mostly limited to the few friends you have, and you already have access to most of that data anyways

**Comment by madsmtm** [comment]
Looking at the `git` history, the project has existed since 18. April 2015, however, there was a period of time (around half a year, if I recall correctly), where the project was without a maintainer, so you could say that's the closest it's been to being "shut down" ;)

**Comment by Ewa321** [comment]
I'm thinking of using this for our final year project. I hope it will continue working. Thanks for your answers btw :)
