### ISSUE TITLE
Sending Link when running fbchat in a VPS

### ISSUE THREAD

**Issue by cavin12400** [carpedm20/fbchat#328]
Does anybody know how to go around in this error? 
When I'm running fbchat on my own device(Windows 10) it's working fine in sending link messages. But when I start to run fbchat on a VPS (Linux Ubuntu 16) it fails to send links after a while. I tried using proxy with TOR but then again it only works for a while then gets the same errors right after.

**Comment by madsmtm** [comment]
How are you sending the links? With just `Client.send` / `Client.sendMessage`? If so, are you sure it's specific to links, and not all messages? Can you try supplying some log output?

My guess is that the problem lies in the fact that the server is on a different IP, maybe Facebook doesn't like that IP for some reason?

**Comment by Schmavery** [comment]
fwiw this sounds like some throttling/spam detection on facebook end in my experience. They seem to apply different rules to links, in particular requiring captchas before link can be sent when they suspect foul play

**Comment by madsmtm** [comment]
See https://github.com/carpedm20/fbchat/issues/477#issuecomment-549369966. I'm closing this issue in favor of that issue, since they seem to be related.
