### ISSUE TITLE
How can I fetch all the unseen messages in a group? 

### ISSUE THREAD

**Issue by AshrafAkon** [carpedm20/fbchat#349]
I am trying to fetch all the unseen message from a Facebook group. Is there any way to do that?

**Comment by madsmtm** [comment]
You could probably use `Client.fetchThreadMessages` in a loop, and then look at the returning messages' `Message.is_read`, to figure out when to stop the loop. But no, there's no direct way

**Comment by adbenitez** [comment]
it would be really useful to have a "`getUnread`" method in the `Thread` class, I also need to get the unread messages, the `Client.fetchThreadMessages` has a `before` parameter that is a timestamp, this doesn't sounds a good way to loop to get the unread messages, currently I am setting limit=1 and iterating while the message is unread, because I don't want to get all messages and then discard the read messages, but this "before" parameter doesn't seems to be as good as an offset, maybe I will lost messages becasue they have the same timestamp and I am getting one message at the time and then setting "before" to the message's timestamp

**Comment by adbenitez** [comment]
actually what I tried of using the timestamp of the latest message I fetched with `Client.fetchThreadMessages` as the `before` parameter doesn't works, it  always return the same message

**Comment by madsmtm** [comment]
Hmm, if the `before` parameter doesn't work, then that's an issue in itself (which you may open if you feel like it)! But the reason it exist is not because we want it to, it's because that's what Facebook gives us to work with 😉

**Comment by madsmtm** [comment]
Closing, since this probably can't be fixed. Feel free to reopen if you find anything useful!
