### ISSUE TITLE
r.text.split('"client_revision":', 1)[1].split(",", 1)[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by vinc3nt** [carpedm20/fbchat#431]
when using useragent like this  
user_agent ="Mozilla/5.0 (Linux; U; Android 8.1.0; ASUS_X00TD Build/OPM1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.89 Mobile Safari/537.36 OPR/43.2.2254.140293"
this error pops up everything works fine when using small useragents  however this isnt limited to only this useragent 

Traceback (most recent call last):
  File "C:\Users\vin\Desktop\fbvinbot\main.py", line 114, in <module>
    client = EchoBot(email , pas,session_cookies = cookies, user_agent=user_agent)
  File "C:\Python27\lib\site-packages\fbchat\_client.py", line 102, in __init__
    self.login(email, password, max_tries)
  File "C:\Python27\lib\site-packages\fbchat\_client.py", line 499, in login
    login_successful, login_url = self._login()
  File "C:\Python27\lib\site-packages\fbchat\_client.py", line 369, in _login
    self._postLogin()
  File "C:\Python27\lib\site-packages\fbchat\_client.py", line 337, in _postLogin
    r.text.split('"client_revision":', 1)[1].split(",", 1)[0]
IndexError: list index out of range

**Comment by madsmtm** [comment]
I've tested this, and can confirm your findings. The reason you're getting that error is because the user agent you've specified resembles a mobile phone - Which means we're being redirected to `m.facebook.com`. The code for finding the `client_revision` assumes that it sees the desktop home page, and for that reason it crashes.

Your best bet? Don't use a user agent that resembles a mobile phone 😉. I'm guessing that even if I did fix this, a lot of code elsewhere makes the same assumption, so I'll close this as "wontfix".
