### ISSUE TITLE
How can I know the last online time of a friend? [eom]

### ISSUE THREAD

**Issue by vimukthi-cl** [carpedm20/fbchat#49]

**Comment by madsmtm** [comment]
@JarbasAI did some work on this in #172. This means that you can now overwrite the event `Client.onChatTimestamp()`, and use the `Client.listen()` method until you receive your data.

I don't think a specific function like `retrieveEOM()` will be possible, because I don't think Facebook has specific functionality to do so, so therefore I'll close this ;)
