### ISSUE TITLE
How can I get message_count by individuals in a thread?

### ISSUE THREAD

**Issue by MShafquat** [carpedm20/fbchat#554]
Using `client.fetchThreadInfo()` method, I can get the total message_count. But I want to know how many messages are sent by an individual in a thread. Is that possible?

**Comment by madsmtm** [comment]
You can't really do that, since it's not something Facebook directly exposes to us.

You'll have to do it manually, by downloading every message in the thread, by some clever use of [`fetchThreadMessages`](https://fbchat.readthedocs.io/en/stable/_modules/fbchat/_client.html#Client.fetchThreadMessages).

Maybe you could even [download your information](https://www.facebook.com/dyi/), and extract the data from there?

**Comment by madsmtm** [comment]
I'll close this for now, feel free to ask further questions though!
